<?php
return [
    "products" => [
        // STEFANIA
        // 1 ---------------------------------------------------------------------------------------------------------------
        [
            "name" => "Spaghetti alla crema di carciofi e zafferano",
            "restaurant_id" => 1,
            "img" => "uploads/metropolitan-pasta.jpg",
            "isVisible" => true,
            "description" => "Primo piatto raffinato e gustoso semplice da realizzare, dove il protagonista assoluto è il formaggio Tuma dla paja che, con la sua cremosità, riesce a conferire alla crema di carciofi una giusta fluidità e consistenza.",
            "price" => 14.00,
        ],
        [
            "name" => "Piovra con crema di lenticchie, bufala e gamberi",
            "restaurant_id" => 1,
            "img" => "uploads/metropolitan-gamberi.jpg",
            "isVisible" => true,
            "description" => "Tentacolo di priovra brasato, gamberi, crema di lenticchie rosse e stracciatella di mozzarella di bufala. Piatto Gluten Free.",
            "price" => 28.00,
        ],
        [
            "name" => "Cotoletta alla milanese",
            "restaurant_id" => 1,
            "img" => "uploads/metropolitan-cotoletta.jpg",
            "isVisible" => true,
            "description" => "Costoletta di vitello con letto di rucola e pomodorini ciliegino e contorno di patate al forno con buccia.",
            "price" => 24.00,
        ],
        [
            "name" => "Risotto alla milanese",
            "restaurant_id" => 1,
            "img" => "uploads/metropolitan-risotto.jpg",
            "isVisible" => true,
            "description" => "Risotto mantecato alla milanese con animelle di vitello dorato, uno dei primi piatti fra i più rappresentativi della cucina lombarda.",
            "price" => 21.00,
        ],
        [
            "name" => "Sformato di patate e verza",
            "restaurant_id" => 1,
            "img" => "uploads/metropolitan-sformato.jpg",
            "isVisible" => true,
            "description" => "Sformatino di patate e verza al profumo di porro e crema di topinambur rigorosamente gluten-free.",
            "price" => 21.00,
        ],
        [
            "name" => "Tortino al cioccolato",
            "restaurant_id" => 1,
            "img" => "uploads/metropolitan-tortino.jpg",
            "isVisible" => true,
            "description" => "Tortino con cuore morbido al cioccolato fondente ed accompagnamento di fragole di Maletto IGP e gelato alla vaniglia del Madagascar. Piatto Gluten Free.",
            "price" => 7.00,
        ],
        [
            "name" => "Tartare di manzo",
            "restaurant_id" => 1,
            "img" => "uploads/metropolitan-tartare.jpg",
            "isVisible" => true,
            "description" => "Tartare di battuta di manzo ai fiocchi di sale rosa, granella di pistacchi e capperi servita con insalata croccante di puntarelle. Piatto Gluten Free.",
            "price" => 19.00,
        ],
        // 2 ---------------------------------------------------------------------------------------------------------------
        [
            "name" => "Pizza Cleto",
            "restaurant_id" => 2,
            "img" => "uploads/bambarra-cleto.jpg",
            "isVisible" => true,
            "description" => "Pizza Gourmet con pomodoro, fior di latte, funghi, pomodorini, olive verdi, capperi, cipolla, ‘nduja. Piatto Gluten Free.",
            "price" => 11.00,
        ],

        [
            "name" => "Pizza Mortazza",
            "restaurant_id" => 2,
            "img" => "uploads/bambarra-mortazza.jpg",
            "isVisible" => true,
            "description" => "Pizza Gourmet con fior di latte, stracciatella, pesto di pistacchio, granella di pistacchio, mortadella IGP Bologna. Piatto Gluten Free.",
            "price" => 12.00,
        ],
        [
            "name" => "Pizza Margherita",
            "restaurant_id" => 2,
            "img" => "uploads/bambarra-margherita.jpg",
            "isVisible" => true,
            "description" => "Pizza margherita classica con pomodoro, mozzarella fior di latte e basilico fresco.",
            "price" => 6.00,
        ],
        [
            "name" => "Spaghetti Cacio e Pepe",
            "restaurant_id" => 2,
            "img" => "uploads/bambarra-cacio.jpg",
            "isVisible" => true,
            "description" => "Classico spaghetto della tradizione romana con pepe nero in grani e pecorino con stagionatura media.",
            "price" => 9.00,
        ],
        [
            "name" => "Linguine alle vongole veraci",
            "restaurant_id" => 2,
            "img" => "uploads/bambarra-vongole.jpg",
            "isVisible" => true,
            "description" => "Linguine di pasta di Gragnano IGP con vongole veraci del Mare Adriatico, aglio, olio, prezzemolo.",
            "price" => 15.00,
        ],
        [
            "name" => "Tagliata di manzo",
            "restaurant_id" => 2,
            "img" => "uploads/bambarra-tagliata.jpg",
            "isVisible" => true,
            "description" => "Tagliata di manzo australiano con sale, pepe bianco e contorno di patate arrosto. Piatto Gluten Free.",
            "price" => 21.00,
        ],
        // 3 ---------------------------------------------------------------------------------------------------------------
        [
            "name" => "Pizza Regina Margherita",
            "restaurant_id" => 3,
            "img" => "uploads/reginamargherita-margherita.jpg",
            "isVisible" => true,
            "description" => "Pizza margherita classica con pomodoro, mozzarella fior di latte e basilico fresco.",
            "price" => 5.00,
        ],
        [
            "name" => "Pizza Salsiccia e Friarielli",
            "restaurant_id" => 3,
            "img" => "uploads/reginamargherita-friarielli.jpg",
            "isVisible" => true,
            "description" => "Pizza con provola, friarielli e salsiccia.",
            "price" => 8.00,
        ],
        [
            "name" => "Pizza Capricciosa",
            "restaurant_id" => 3,
            "img" => "uploads/reginamargherita-capricciosa.jpg",
            "isVisible" => true,
            "description" => "Pizza con pomodoro, mozzarella fior di latte, prosciutto cotto, funghi champignon e carciofi.",
            "price" => 7.00,
        ],
        [
            "name" => "Pizza Diavola",
            "restaurant_id" => 3,
            "img" => "uploads/reginamargherita-diavola.jpg",
            "isVisible" => true,
            "description" => "Pizza con pomodoro, mozzarella fior di latte, salame piccante ed olive nere.",
            "price" => 9.00,
        ],
        [
            "name" => "Pizza alla marinara",
            "restaurant_id" => 3,
            "img" => "uploads/reginamargherita-marinara.jpg",
            "isVisible" => true,
            "description" => "Pizza con doppio pomodoro, aglio ed origano fresco.",
            "price" => 4.00,
        ],
        [
            "name" => "Pizza fritta",
            "restaurant_id" => 3,
            "img" => "uploads/reginamargherita-fritta.jpg",
            "isVisible" => true,
            "description" => "Pizza fritta ripiena di ricotta, cicoli, pomodoro San Marzano, pepe, provola e basilico fresco.",
            "price" => 5.00,
        ],
        // 4 ---------------------------------------------------------------------------------------------------------------
        [
            "name" => "Pizza Crudo",
            "restaurant_id" => 4,
            "img" => "uploads/fradiavolo-crudo.jpg",
            "isVisible" => true,
            "description" => "Pizza con pomodoro La Fiammante, fiordilatte di Agerola La Montanina, prosciutto crudo Raspini selezione Fra Diavolo, gocce di parmigiano, basilico, olio EVO.",
            "price" => 10.00,
        ],
        [
            "name" => "Pizza  La Trombetta",
            "restaurant_id" => 4,
            "img" => "uploads/fradiavolo-latrombetta.jpg",
            "isVisible" => true,
            "description" => "Pizza Gourmet con crema di fiordilatte, crema di zucchine, stracciatella, salmone affumicato, misticanza, sale nero, olio EVO.",
            "price" => 12.00,
        ],
        [
            "name" => "Pizza Prosciutto Cotto",
            "restaurant_id" => 4,
            "img" => "uploads/fradiavolo-cotto.jpg",
            "isVisible" => true,
            "description" => "Pizza con pomodoro La Fiammante, fiordilatte di Agerola La Montanina, prosciutto cotto Raspini selezione Fra Diavolo, provolone del Monaco DOP, Parmigiano Reggiano DOP.",
            "price" => 9.00,
        ],
        [
            "name" => "Pizza Fichi Si Nasce!",
            "restaurant_id" => 4,
            "img" => "uploads/fradiavolo-fichi.jpg",
            "isVisible" => true,
            "description" => "Pizza con impasto nero, fiordilatte di Agerola, prosciutto crudo di Norcia Renzini IGP, stracciatella, mostarda di fichi, Parmigiano Reggiano DOP, basilico, olio EVO.",
            "price" => 9.00,
        ],
        [
            "name" => "Pizza Margherita",
            "restaurant_id" => 4,
            "img" => "uploads/fradiavolo-margherita.jpg",
            "isVisible" => true,
            "description" => "Pizza con pomodoro La Fiammante, fiordilatte di Agerola La Montanina, parmigiano Reggiano DOP, basilico, olio EVO.",
            "price" => 4.00,
        ],
        [
            "name" => "Crocchetta Mortadella e Pistacchio",
            "restaurant_id" => 4,
            "img" => "uploads/fradiavolo-crocchetta.jpg",
            "isVisible" => true,
            "description" => "Crocchetta con patate rosse, mozzarella, mortadella con pistacchio Raspini selezione Fra Diavolo, pesto di pistacchio.",
            "price" => 3.00,
        ],
        // 5 ---------------------------------------------------------------------------------------------------------------
        [
            "name" => "Lasagna alla bolognese",
            "restaurant_id" => 5,
            "img" => "uploads/sanbiagio-lasagna.jpg",
            "isVisible" => true,
            "description" => "Classica lasagna con pasta fresca all'uovo verde di spinaci, besciamella, ragù.",
            "price" => 9.00,
        ],
        [
            "name" => "Tagliatelle al ragù",
            "restaurant_id" => 5,
            "img" => "uploads/sanbiagio-tagliatelle.jpg",
            "isVisible" => true,
            "description" => "Tagliatelle di pasta fresca all'uovo con ragù classico bolognese di manzo, pomodoro e pancetta",
            "price" => 8.00,
        ],
        [
            "name" => "Tortellini in brodo",
            "restaurant_id" => 5,
            "img" => "uploads/sanbiagio-tortellini.jpg",
            "isVisible" => true,
            "description" => "Tortellini di pasta fresca all'uovo con brodo di cappone.",
            "price" => 12.00,
        ],
        [
            "name" => "Tagliere tradizionale con tigelle e crescentine",
            "restaurant_id" => 5,
            "img" => "uploads/sanbiagio-tagliere.jpg",
            "isVisible" => true,
            "description" => "Tagliere per 2 persone di salumi, formaggi, verdure grigliate e pesto modenese accompagnato con tigelle e crescentine fresche.",
            "price" => 15.00,
        ],
        [
            "name" => "Tortelli di zucca",
            "restaurant_id" => 5,
            "img" => "uploads/sanbiagio-tortelli.jpg",
            "isVisible" => true,
            "description" => "Tortelli di pasta fresca all'uovo con ripieno di ricotta, pepe, noce moscata e crema di zucca.",
            "price" => 21.00,
        ],
        [
            "name" => "Torta Tenerina",
            "restaurant_id" => 5,
            "img" => "uploads/sanbiagio-tenerina.jpg",
            "isVisible" => true,
            "description" => "Torta tipica ferrarese al cioccolato fondente accompagnata con panna fresca montata e scorza di limone. Piatto Gluten Free.",
            "price" => 6.00,
        ],
        // 6 ---------------------------------------------------------------------------------------------------------------
        [
            "name" => "Pizza Ortolana",
            "restaurant_id" => 6,
            "img" => "uploads/malerba-ortolana.jpg",
            "isVisible" => true,
            "description" => "Pizza con pomodoro, fior di latte, zucchine e melanzane grigliate, peperoni gialli arrosto. Piatto Gluten Free.",
            "price" => 11.00,
        ],
        [
            "name" => "Pizza agli asparagi",
            "restaurant_id" => 6,
            "img" => "uploads/malerba-asparagi.jpg",
            "isVisible" => true,
            "description" => "Pizza con mozzarella vegana, crema di asparagi, piselli freschi e polvere di formaggio vegano. Piatto Gluten Free.",
            "price" => 12.00,
        ],
        [
            "name" => "Spaghetti vegani con ragù",
            "restaurant_id" => 6,
            "img" => "uploads/malerba-spaghetti.jpg",
            "isVisible" => true,
            "description" => "Spaghetti con ragù di lenticchie e noci. Piatto Gluten Free.",
            "price" => 10.00,
        ],
        [
            "name" => "Pasta alla Carbonara vegana",
            "restaurant_id" => 6,
            "img" => "uploads/malerba-carbonara.jpg",
            "isVisible" => true,
            "description" => "Pasta con panna di soia, seitan affumicato, curcuma e pepe. Piatto Gluten Free.",
            "price" => 13.00,
        ],
        [
            "name" => "Burger di barbabietola rossa",
            "restaurant_id" => 6,
            "img" => "uploads/malerba-burger.jpg",
            "isVisible" => true,
            "description" => "Burger vegano di barbabietola rossa e lenticchie accompagnato con pane gruten free ai 5 cereali, pomodoro, cipolle caramellate e misticanza di stagione. Piatto Gluten Free.",
            "price" => 10.00,
        ],
        [
            "name" => "Torta Sacher vegana",
            "restaurant_id" => 6,
            "img" => "uploads/malerba-sacher.jpg",
            "isVisible" => true,
            "description" => "Torta Sacher gluten free e vegana con latte vegetale, farina di riso farcita con una composta di albicocche. Piatto Gluten Free.",
            "price" => 8.00,
        ],
        // 7 ---------------------------------------------------------------------------------------------------------------
        [
            "name" => "Pink and White Risotto",
            "restaurant_id" => 7,
            "img" => "uploads/soulgreen-risotto.jpg",
            "isVisible" => true,
            "description" => "Cremoso risotto mantecato con barbabietola, mandorle croccanti e stracchino vegano a base di arachidi.",
            "price" => 18.00,
        ],
        [
            "name" => "Gnocchi con zucca e tartufo nero",
            "restaurant_id" => 7,
            "img" => "uploads/soulgreen-gnocchi.jpg",
            "isVisible" => true,
            "description" => "Gnocchi artigianali al cavolfiore senza glutine conditi con zucca, burro di nocciola e tartufo nero. Piatto Gluten Free.",
            "price" => 18.00,
        ],
        [
            "name" => "Quinoa Salad",
            "restaurant_id" => 7,
            "img" => "uploads/soulgreen-quinoa.jpg",
            "isVisible" => true,
            "description" => "Fresca insalata proteica di quinoa arricchita con un mix di verdure croccanti, pomodori secchi, melograno e vinaigrette. Piatto Gluten Free.",
            "price" => 9.00,
        ],
        [
            "name" => "Falafel Wrap",
            "restaurant_id" => 7,
            "img" => "uploads/soulgreen-wrap.jpg",
            "isVisible" => true,
            "description" => "Wrap con falafel di ceci e spinaci, coleslaw, pomodoro, servito con le nostre patatine Crisp and Dips.",
            "price" => 15.00,
        ],
        [
            "name" => "Soul Avocado Toast",
            "restaurant_id" => 7,
            "img" => "uploads/soulgreen-toast.jpg",
            "isVisible" => true,
            "description" => "Toast con pane, pomodoro grigliato, fresco guacamole e slice di avocado con topping di semi misti e pistacchi, servito con le nostre patatine Crisp and Dips.",
            "price" => 10.00,
        ],
        [
            "name" => "Raspberry Cheesecake",
            "restaurant_id" => 7,
            "img" => "uploads/soulgreen-cheesecake.jpg",
            "isVisible" => true,
            "description" => "Fresca cheesecake al lampone a base di anacardi, su un biscotto di mandorle ed avena, ricoperta da glassa ai lamponi e servita con sorbetto ai lamponi, fragole e terra di cioccolato.",
            "price" => 12.00,
        ],
        // 8 ---------------------------------------------------------------------------------------------------------------
        [
            "name" => "Tonnarelli Cacio e Pepe",
            "restaurant_id" => 8,
            "img" => "uploads/grappolo-tonnarelli.jpg",
            "isVisible" => true,
            "description" => "Tonnarelli con pecorino romano DOP e pepe.",
            "price" => 12.00,
        ],
        [
            "name" => "Rigatoni alla matriciana",
            "restaurant_id" => 8,
            "img" => "uploads/grappolo-matriciana.jpg",
            "isVisible" => true,
            "description" => "Rigatoni con guanciale, pecorino romano DOP e pomodori pelati.",
            "price" => 12.00,
        ],
        [
            "name" => "Coda alla Vaccinara",
            "restaurant_id" => 8,
            "img" => "uploads/grappolo-coda.jpg",
            "isVisible" => true,
            "description" => "Coda di bue stufata lentamente con pomodori pelati e salsa di pinoli, uvetta e cacao amaro.",
            "price" => 15.00,
        ],
        [
            "name" => "Carciofi alla Giudia",
            "restaurant_id" => 8,
            "img" => "uploads/grappolo-giudia.jpg",
            "isVisible" => true,
            "description" => "Carciofo fritto tipico della cucina romana. Piatto Gluten Free.",
            "price" => 18.00,
        ],
        [
            "name" => "Panzanella",
            "restaurant_id" => 8,
            "img" => "uploads/grappolo-panzanella.jpg",
            "isVisible" => true,
            "description" => "Piatto tipico della cucina toscana ed in generale delle regioni del centro Italia. Un’insalata di Pomodori, Cipolle e Olive alla quale si aggiunge il pane duro ammollato nell’acqua e strizzato.",
            "price" => 6.50,
        ],
        [
            "name" => "Crostata con visciole e ricotta",
            "restaurant_id" => 8,
            "img" => "uploads/grappolo-crostata.jpg",
            "isVisible" => true,
            "description" => "Crostata di frolla aromatizzata alla vaniglia e limone con confettura di visciole e ricotta vaccina.",
            "price" => 5.00,
        ],
        // 9 ---------------------------------------------------------------------------------------------------------------
        [
            "name" => "Jungle BBQ",
            "restaurant_id" => 9,
            "img" => "uploads/flower-jungle.png",
            "isVisible" => true,
            "description" => "Immergiti nel ricco gusto della giungla servito in un bun verde con semi di sesamo neri. Il sapore smoky della salsa bbq e della salsa wild si accompagna perfettamente al burger di avena e fagioli. Zucchine al forno, flower cheddar, insalata e pomodori completano questo saziante e delizioso panino.",
            "price" => 12.00,
        ],

        [
            "name" => "Spicy Cecio",
            "restaurant_id" => 9,
            "img" => "uploads/flower-cecio.jpg",
            "isVisible" => true,
            "description" => "Il giallo intenso del pane è dato dalla curcuma, il sapore è speziato e leggermente piccante. Il verde acceso dello spinacino e le sfumature viola delle cipolle caramellate danno forma alle tonalità vivaci del burger",
            "price" => 13.00,
        ],
        [
            "name" => "Cherry Bomb",
            "restaurant_id" => 9,
            "img" => "uploads/flower-bomb.jpg",
            "isVisible" => true,
            "description" => "Il Cherry Bomb vince il premio di burger più instagrammato e più richiesto del menu. Merito della tonalità rosa intenso del pane e del suo mix di ingredienti che lo rendono una bomba di sapori: disco di lenticchie e riso basmati, pomodori confit, salsa Rocktail e germogli di soia.",
            "price" => 12.00,
        ],
        [
            "name" => "Purple Cheesy",
            "restaurant_id" => 9,
            "img" => "uploads/flower-purple.png",
            "isVisible" => true,
            "description" => "Il nostro patty di lenticchie è accompagnato da una fetta di formaggio vegetale e dal sapore deciso della salsa smoky. Il tutto è racchiuso tra due fette di bun viola.",
            "price" => 12.00,
        ],
        [
            "name" => "Cacao Mousse",
            "restaurant_id" => 9,
            "img" => "uploads/flower-mousse.jpg",
            "isVisible" => true,
            "description" => "Mousse a base di cacao e avocado, con croccante di nocciole e coulis di frutti rossi. Piatto Gluten Free.",
            "price" => 8.00,
        ],
        [
            "name" => "Flower Bombs",
            "restaurant_id" => 9,
            "img" => "uploads/flower-seitan-bombs.jpg",
            "isVisible" => true,
            "description" => "Bombs di seitan e fagioli Red Kidney, una vera esplosione di gusto! Il mix perfetto per i migliori aperitivi. Piatto Gluten Free.",
            "price" => 6.50,
        ],
        // CRISTIAN
        // 10 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Sunny Salmon",
            "img" => "uploads/sunny-salmon.jpg",
            "isVisible" => true,
            "restaurant_id" => 10,
            "description" => "Riso Bianco, Juicy Salmon, Avocado, Edamame, Cavolo Rosso, Salsa Speciale, Crema di Avocado, Sesamo",
            "price" => 9.90,
        ],
        [
            "name" => "Spicy Tuna",
            "img" => "uploads/spicy-tuna.jpg",
            "isVisible" => true,
            "restaurant_id" => 10,
            "description" => "Riso Bianco, Tonno, Goma Wakame, Cavolo Rosso, Carote, Cetrioli, Salsa Ponzu, Salsa Spicy Peanuts, Jalapeño, Cipolla Croccante, Tobiko, Sesamo",
            "price" => 10.90,
        ],
        [
            "name" => "Vegan",
            "img" => "uploads/vegan.jpg",
            "isVisible" => true,
            "restaurant_id" => 10,
            "description" => "Quinoa, Tofu Grigliato Bio, Ceci, Carote, Avocado, Salsa Teriyaki, Patata Dolce Croccante, Sesamo",
            "price" => 10.90,
        ],
        [
            "name" => "Roast Beef",
            "img" => "uploads/roast-beef.jpg",
            "isVisible" => true,
            "restaurant_id" => 10,
            "description" => "Riso Integrale, Roast Beef all'inglese, Pomodorini, Avocado, Germogli di Soia, Feta, Aromatic Ginger Oil, House Tartar, Mandorle, Sesamo",
            "price" => 10.90,
        ],
        [
            "name" => "Chicken",
            "img" => "uploads/chicken.jpg",
            "isVisible" => true,
            "restaurant_id" => 10,
            "description" => "Riso Bianco, Pollo Teriyaki e Zenzero, Zucchine, Pomodorini, Cavolo Rosso, Salsa Teriyaki, Salsa Spicy Mayo, Cipollotto, Mandorle, Sesamo",
            "price" => 9.90,
        ],
        [
            "name" => "Acai House Bowl",
            "img" => "uploads/acai.jpg",
            "isVisible" => true,
            "restaurant_id" => 10,
            "description" => "Acai, Banana, Lamponi, Mandorla, Gocce di Cioccolato, Nut Butter",
            "price" => 7.50,
        ],
        // 11 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Salmon Poké",
            "img" => "uploads/Salmon-Poke.jpeg",
            "isVisible" => true,
            "restaurant_id" => 11,
            "description" => "Salmone, avocado, edamame, goma wakame, sesamo",
            "price" => 11.50,
        ],
        [
            "name" => "Tuna Poké",
            "img" => "uploads/tuna.jpg
            ",
            "isVisible" => true,
            "restaurant_id" => 11,
            "description" => "Tonno, cetrioli, goma wakame, avocado, sesamo",
            "price" => 11.50,
        ],
        [
            "name" => "Chicken Poké",
            "img" => "uploads/Chicken-Poke.jpg",
            "isVisible" => true,
            "restaurant_id" => 11,
            "description" => "Pollo, pomodorini, feta, olive",
            "price" => 11.50,
        ],
        [
            "name" => "Salmon Spicy Poké",
            "img" => "uploads/Spicy-Salmon-Poke.jpg",
            "isVisible" => true,
            "restaurant_id" => 11,
            "description" => "Salmone marinato con maionese spicy , edamame, avocado, cipolla fritta",
            "price" => 11.50,
        ],
        [
            "name" => "Almond Tartare",
            "img" => "uploads/almond.jpg",
            "isVisible" => true,
            "restaurant_id" => 11,
            "description" => "Riso bianco, avocado, salmone, mandorle e sesamo, mayo spicy e teriyaki* Può contenere tracce di GlutineIncluso una porzione di Wasabi e Zenzero",
            "price" => 4.90,
        ],
        [
            "name" => "Crispy Tuna",
            "img" => "uploads/crispy.jpeg",
            "isVisible" => true,
            "restaurant_id" => 11,
            "description" => "Riso bianco, avocado, tartare di tonno, sesamo e cipolla croccante, mayo spicy e teriyaki* Può contenere tracce di GlutineIncluso una porzione di Wasabi e Zenzero",
            "price" => 4.90,
        ],
        // 12 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Chicken up Kebab",
            "img" => "uploads/Kebab.jpeg",
            "isVisible" => true,
            "restaurant_id" => 12,
            "description" => "Kebab di pollo 100% italiano, cipolla caramellata, lattuga, maionese limone e pepe nero by Heinz.",
            "price" => 5.90,
        ],
        [
            "name" => "Angus Classic Kebab",
            "img" => "uploads/Kebab.jpeg",
            "isVisible" => true,
            "restaurant_id" => 12,
            "description" => "Kebab di black angus, pomodori, cipolla, lattuga, salsa yogurt, salsa piccante.",
            "price" => 8.90,
        ],
        [
            "name" => "American Kebab",
            "img" => "uploads/american.jpg",
            "isVisible" => true,
            "restaurant_id" => 12,
            "description" => "Kebab di black angus, bacon, cheddar, lattuga, salsa bacon burger by Heinz.",
            "price" => 8.90,
        ],
        // 13 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Panino Kebab",
            "img" => "uploads/panino-kebab.jpg",
            "isVisible" => true,
            "restaurant_id" => 13,
            "description" => "Carne kebab e pane",
            "price" => 6.00,
        ],
        [
            "name" => "Piadina Kebab",
            "img" => "uploads/piadina-kebab.jpeg",
            "isVisible" => true,
            "restaurant_id" => 13,
            "description" => "Carne kebab e piadina",
            "price" => 5.00,
        ],
        [
            "name" => "Kebab al Piatto",
            "img" => "uploads/piatto-kebab.jpeg",
            "isVisible" => true,
            "restaurant_id" => 13,
            "description" => "Carne kebab con verdure",
            "price" => 7.00,
        ],
        [
            "name" => "Falafel",
            "img" => "uploads/falafel-di-ceci.jpg",
            "isVisible" => true,
            "restaurant_id" => 13,
            "description" => "4 Polpette di ceci e spezie",
            "price" => 4.00,
        ],
        [
            "name" => "Halawa",
            "img" => "uploads/halawa.jpeg",
            "isVisible" => true,
            "restaurant_id" => 13,
            "description" => "Pasta di semi di girasole e frutta secca",
            "price" => 1.50,
        ],
        [
            "name" => "Baklava",
            "img" => "uploads/Baklawa-Sweets.jpg",
            "isVisible" => true,
            "restaurant_id" => 13,
            "description" => "Pasta fillo, frutta secca e sciroppo di miele",
            "price" => 1.50,
        ],
        // 14 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Panino Kebab",
            "img" => "uploads/panino-kebab.jpg",
            "isVisible" => true,
            "restaurant_id" => 14,
            "description" => "Carne kebab e pane",
            "price" => 6.00,
        ],
        [
            "name" => "Piadina Kebab",
            "img" => "uploads/piadina-kebab.jpeg",
            "isVisible" => true,
            "restaurant_id" => 14,
            "description" => "Carne kebab e piadina",
            "price" => 5.00,
        ],
        [
            "name" => "Kebab al Piatto",
            "img" => "uploads/piatto-kebab.jpeg",
            "isVisible" => true,
            "restaurant_id" => 14,
            "description" => "Carne kebab con verdure",
            "price" => 7.00,
        ],
        [
            "name" => "Falafel",
            "img" => "uploads/falafel-di-ceci.jpg",
            "isVisible" => true,
            "restaurant_id" => 14,
            "description" => "4 Polpette di ceci e spezie",
            "price" => 4.00,
        ],
        [
            "name" => "Halawa",
            "img" => "uploads/halawa.jpeg",
            "isVisible" => true,
            "restaurant_id" => 14,
            "description" => "Pasta di semi di girasole e frutta secca",
            "price" => 1.50,
        ],
        [
            "name" => "Baklava",
            "img" => "uploads/Baklawa-Sweets.jpg",
            "isVisible" => true,
            "restaurant_id" => 14,
            "description" => "Pasta fillo, frutta secca e sciroppo di miele",
            "price" => 1.50,
        ],
        // 15 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Panino Kebab",
            "img" => "uploads/panino-kebab.jpg",
            "isVisible" => true,
            "restaurant_id" => 15,
            "description" => "Carne kebab e pane",
            "price" => 6.00,
        ],
        [
            "name" => "Piadina Kebab",
            "img" => "uploads/piadina-kebab.jpeg",
            "isVisible" => true,
            "restaurant_id" => 15,
            "description" => "Carne kebab e piadina",
            "price" => 5.00,
        ],
        [
            "name" => "Kebab al Piatto",
            "img" => "uploads/piatto-kebab.jpeg",
            "isVisible" => true,
            "restaurant_id" => 15,
            "description" => "Carne kebab con verdure",
            "price" => 7.00,
        ],
        [
            "name" => "Falafel",
            "img" => "uploads/falafel-di-ceci.jpg",
            "isVisible" => true,
            "restaurant_id" => 15,
            "description" => "4 Polpette di ceci e spezie",
            "price" => 4.00,
        ],
        [
            "name" => "Halawa",
            "img" => "uploads/halawa.jpeg",
            "isVisible" => true,
            "restaurant_id" => 15,
            "description" => "Pasta di semi di girasole e frutta secca",
            "price" => 1.50,
        ],
        [
            "name" => "Baklava",
            "img" => "uploads/Baklawa-Sweets.jpg",
            "isVisible" => true,
            "restaurant_id" => 15,
            "description" => "Pasta fillo, frutta secca e sciroppo di miele",
            "price" => 1.50,
        ],
        // 16 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Chana Masala",
            "img" => "uploads/chana-masala-recipe.jpg",
            "isVisible" => true,
            "restaurant_id" => 16,
            "description" => "Ceci con cipolla, pomodoro e spezie",
            "price" => 6.00,
        ],
        [
            "name" => "Chicken Tikka Masala",
            "img" => "uploads/chicken-tikka-masala.jpeg",
            "isVisible" => true,
            "restaurant_id" => 16,
            "description" => "Pollo con pomodori e spezie",
            "price" => 7.00,
        ],
        [
            "name" => "Goa Fish Curry",
            "img" => "uploads/Goan-Fish-Curry-1.jpg",
            "isVisible" => true,
            "restaurant_id" => 16,
            "description" => "Bocconcini di rana pescatrice con latte di cocco",
            "price" => 7.00,
        ],
        [
            "name" => "Balti Gamberi",
            "img" => "uploads/balti.jpeg",
            "isVisible" => true,
            "restaurant_id" => 16,
            "description" => "Gamberi saltati con latte di cocco, zenzero e cipolla fritta",
            "price" => 8.50,
        ],
        [
            "name" => "Chicken Shahi Kurma",
            "img" => "uploads/shahi-korma.jpg",
            "isVisible" => true,
            "restaurant_id" => 16,
            "description" => "Pollo in salsa di pomodoro, anacardi e spezie",
            "price" => 7.00,
        ],
        [
            "name" => "Mutter aloo palak",
            "img" => "uploads/aloo-palak-recipe.jpg",
            "isVisible" => true,
            "restaurant_id" => 16,
            "description" => "Piselli e patate in crema di spinaci",
            "price" => 6.00,
        ],
        // 17 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Chana Masala",
            "img" => "uploads/chana-masala-recipe.jpg",
            "isVisible" => true,
            "restaurant_id" => 17,
            "description" => "Ceci con cipolla, pomodoro e spezie",
            "price" => 6.00,
        ],
        [
            "name" => "Chicken Tikka Masala",
            "img" => "uploads/chicken-tikka-masala.jpeg",
            "isVisible" => true,
            "restaurant_id" => 17,
            "description" => "Pollo con pomodori e spezie",
            "price" => 7.00,
        ],
        [
            "name" => "Goa Fish Curry",
            "img" => "uploads/Goan-Fish-Curry-1.jpg",
            "isVisible" => true,
            "restaurant_id" => 17,
            "description" => "Bocconcini di rana pescatrice con latte di cocco",
            "price" => 7.00,
        ],
        [
            "name" => "Balti Gamberi",
            "img" => "uploads/balti.jpeg",
            "isVisible" => true,
            "restaurant_id" => 17,
            "description" => "Gamberi saltati con latte di cocco, zenzero e cipolla fritta",
            "price" => 8.50,
        ],
        [
            "name" => "Chicken Shahi Kurma",
            "img" => "uploads/shahi-korma.jpg",
            "isVisible" => true,
            "restaurant_id" => 17,
            "description" => "Pollo in salsa di pomodoro, anacardi e spezie",
            "price" => 7.00,
        ],
        [
            "name" => "Mutter aloo palak",
            "img" => "uploads/aloo-palak-recipe.jpg",
            "isVisible" => true,
            "restaurant_id" => 17,
            "description" => "Piselli e patate in crema di spinaci",
            "price" => 6.00,
        ],
        // 18 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Chana Masala",
            "img" => "uploads/chana-masala-recipe.jpg",
            "isVisible" => true,
            "restaurant_id" => 18,
            "description" => "Ceci con cipolla, pomodoro e spezie",
            "price" => 6.00,
        ],
        [
            "name" => "Chicken Tikka Masala",
            "img" => "uploads/chicken-tikka-masala.jpeg",
            "isVisible" => true,
            "restaurant_id" => 18,
            "description" => "Pollo con pomodori e spezie",
            "price" => 7.00,
        ],
        [
            "name" => "Goa Fish Curry",
            "img" => "uploads/Goan-Fish-Curry-1.jpg",
            "isVisible" => true,
            "restaurant_id" => 18,
            "description" => "Bocconcini di rana pescatrice con latte di cocco",
            "price" => 7.00,
        ],
        [
            "name" => "Balti Gamberi",
            "img" => "uploads/balti.jpeg",
            "isVisible" => true,
            "restaurant_id" => 18,
            "description" => "Gamberi saltati con latte di cocco, zenzero e cipolla fritta",
            "price" => 8.50,
        ],
        [
            "name" => "Chicken Shahi Kurma",
            "img" => "uploads/shahi-korma.jpg",
            "isVisible" => true,
            "restaurant_id" => 18,
            "description" => "Pollo in salsa di pomodoro, anacardi e spezie",
            "price" => 7.00,
        ],
        [
            "name" => "Mutter aloo palak",
            "img" => "uploads/aloo-palak-recipe.jpg",
            "isVisible" => true,
            "restaurant_id" => 18,
            "description" => "Piselli e patate in crema di spinaci",
            "price" => 6.00,
        ],
        // FEDERICO
        // 19 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Baklavas Croccante",
            "img" => "uploads/Vasiliki_kouzina_milano_Baklavas_croccante.jpg",
            "isVisible" => true,
            "restaurant_id" => 19,
            "description" => "Il baklava è un dolce a base di pasta fillo e frutta secca intriso con un goloso sciroppo di miele, molto diffuso nell'area balcanica e mediorientale.",
            "price" => 8,
        ],
        [
            "name" => "Polpo al miele",
            "img" => "uploads/Vasiliki_kouzina_milano_polpo al miele.jpg",
            "isVisible" => true,
            "restaurant_id" => 19,
            "description" => "Polpo glassato al miele, con crema di ceci neri, pomodirini confit e crumble di olive taggiasche",
            "price" => 22,
        ],
        [
            "name" => "Orata allo zafferano",
            "img" => "uploads/Vasiliki_kouzina_milano_Orata allo zafferano.jpg",
            "isVisible" => true,
            "restaurant_id" => 19,
            "description" => "Tenerissimo filetto di orata in salsa allo zafferano, con fagioli",
            "price" => 22,
        ],
        [
            "name" => "Polpette di erbe",
            "img" => "uploads/Vasiliki_kouzina_milano_Polpette.jpg",
            "isVisible" => true,
            "restaurant_id" => 19,
            "description" => "Polpette di erbe e crauti, finocchio e salsa alla feta",
            "price" => 10,
        ],
        [
            "name" => "Involtino di foglie",
            "img" => "uploads/Vasiliki_kouzina_milano_involtino di foglie.jpg",
            "isVisible" => true,
            "restaurant_id" => 19,
            "description" => "Involtino di foglie di vite",
            "price" => 10,
        ],
        [
            "name" => "Fave",
            "img" => "uploads/Vasiliki_kouzina_milano_Fave.jpg",
            "isVisible" => true,
            "restaurant_id" => 19,
            "description" => "Fave, olio evo di Kalamata, uvetta di Corinto, zenzero",
            "price" => 9,
        ],
        // 20 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Baklavas Croccante",
            "img" => "uploads/Ristorante_Greco_Dioniso_Baklava.png",
            "isVisible" => true,
            "restaurant_id" => 20,
            "description" => "Il baklava è un dolce a base di pasta fillo e frutta secca intriso con un goloso sciroppo di miele, molto diffuso nell'area balcanica e mediorientale.",
            "price" => 7,
        ],
        [
            "name" => "Dalmadakia",
            "img" => "uploads/Ristorante_Greco_Dioniso_Dolmadakia.jpg",
            "isVisible" => true,
            "restaurant_id" => 20,
            "description" => "Involtini con foglie di vite ripiene di riso ed erbe aromatiche",
            "price" => 6,
        ],
        [
            "name" => "Keftedekia",
            "img" => "uploads/Ristorante_Greco_Dioniso_Keftedakia.jpg",
            "isVisible" => true,
            "restaurant_id" => 20,
            "description" => "Carne macinata di vitella, mischiata con delle spezie e gli aromi",
            "price" => 13,
        ],
        [
            "name" => "Mussaka",
            "img" => "uploads/Ristorante_Greco_Dioniso_Mussaka.jpeg",
            "isVisible" => true,
            "restaurant_id" => 20,
            "description" => "Tipica specialità greca a base di carne, melanzane e spezie",
            "price" => 10,
        ],
        [
            "name" => "Gyros Pita",
            "img" => "uploads/Ristorante_Greco_Dioniso_gyros_pita.webp",
            "isVisible" => true,
            "restaurant_id" => 20,
            "description" => "Gyros è ripieno di carne di maiale cotta su spiedi, tagliata a fettine sottili e servita arrotolata nelle pite, i tipici pani greci simili alle nostre piadine.",
            "price" => 13,
        ],
        [
            "name" => "Pita souvlaki",
            "img" => "uploads/Ristorante_Greco_Dioniso_Pita_souvlaki.jpeg",
            "isVisible" => true,
            "restaurant_id" => 20,
            "description" => "Il gyros souvlaki è un piatto di carne tipico della cucina greca, realizzato con pita, carne di pollo e salsa tzatziki",
            "price" => 13,
        ],
        // 21 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Bekris Mezès",
            "img" => "uploads/Taverna_Ouzeri_Mykonos_Bekris_Mezes.jpg",
            "isVisible" => true,
            "restaurant_id" => 21,
            "description" => "Carne affogata nel vino",
            "price" => 10,
        ],
        [
            "name" => "Kleftiko",
            "img" => "uploads/Taverna_Ouzeri_Mykonos_Kleftiko.png",
            "isVisible" => true,
            "restaurant_id" => 21,
            "description" => "Spezzatino di agnello in pasta sfoglia",
            "price" => 14,
        ],
        [
            "name" => "Sutzukaria",
            "img" => "uploads/Taverna_Ouzeri_Mykonos_Sutzukaria.jpg",
            "isVisible" => true,
            "restaurant_id" => 21,
            "description" => "Polpette di carne alle spezie in salsa rosa",
            "price" => 10,
        ],
        [
            "name" => "Mussaka",
            "img" => "uploads/Taverna_Ouzeri_Mykonos_moussaka.jpg",
            "isVisible" => true,
            "restaurant_id" => 21,
            "description" => "Tipica specialità greca a base di carne, melanzane e spezie",
            "price" => 9,
        ],
        [
            "name" => "Gyros Pita",
            "img" => "uploads/Taverna_Ouzeri_Mykonos_Gyros_pita.jpg",
            "isVisible" => true,
            "restaurant_id" => 21,
            "description" => "Gyros è ripieno di carne di maiale cotta su spiedi, tagliata a fettine sottili e servita arrotolata nelle pite, i tipici pani greci simili alle nostre piadine.",
            "price" => 14,
        ],
        [
            "name" => "Galaktoboureko",
            "img" => "uploads/Taverna_Ouzeri_Mykonos_Galaktoboureko.jpg",
            "isVisible" => true,
            "restaurant_id" => 21,
            "description" => "torta di pasta fillo farcita con burro, semolino, zucchero, maizena, uova, latte, vaniglia e noce moscata",
            "price" => 6,
        ],
        // 22 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Edamame classico",
            "img" => "uploads/El_Takomaki_Edamame classico.jpeg",
            "isVisible" => true,
            "restaurant_id" => 22,
            "description" => "Fagioli di soia al vapore con sale maldon e limone",
            "price" => 5.5,
        ],
        [
            "name" => "Nachos el Tacomaki",
            "img" => "uploads/El_Takomaki_Nachos_el_tacomaki.jpg",
            "isVisible" => true,
            "restaurant_id" => 22,
            "description" => "Nachos, cipolla rosa, jalapeno, datterini, formaggio filante, guacamole e panna acida",
            "price" => 10.5,
        ],
        [
            "name" => "Albondingas di camaron",
            "img" => "uploads/El_Takomaki_Albondingas.jpg",
            "isVisible" => true,
            "restaurant_id" => 22,
            "description" => "Polpette di mazzancolle, surimi, maionese, ondashi, guacamole e scagli di tonnetto",
            "price" => 10.5,
        ],
        [
            "name" => "Tacos Picanha",
            "img" => "uploads/El_Takomaki_Tacos_picanha.webp",
            "isVisible" => true,
            "restaurant_id" => 22,
            "description" => "Sfoglia di grano ripiena con straccetti di picanha marinata in salsa kimchi, soia e peperoncino",
            "price" => 9,
        ],
        [
            "name" => "Camaron Salteados",
            "img" => "uploads/El_Takomaki_Camarones_Salteados.webp",
            "isVisible" => true,
            "restaurant_id" => 22,
            "description" => "Sfoglia di grano ripiena con mazzancolle saltate, panna acida, crautri, lime e guacamole",
            "price" => 10.5,
        ],
        [
            "name" => "Atun flambé",
            "img" => "uploads/El_Takomaki_atun_flameado.jpg",
            "isVisible" => true,
            "restaurant_id" => 22,
            "description" => "Carpaccio di tonno scottato con salsa ponzu, olio di sesamo, salsa kimchi, pasta kataifi e peperonicino",
            "price" => 16,
        ],
        // 23 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Tris di Tostadas",
            "img" => "uploads/Piedra_del_Sol_Tris_Tostadas.jpg",
            "isVisible" => true,
            "restaurant_id" => 23,
            "description" => "Tostadas di mais farcite con Frijoles e Nopales",
            "price" => 9,
        ],
        [
            "name" => "Nachos el Tacomaki",
            "img" => "uploads/Piedra_del_Sol_Nachos.jpg",
            "isVisible" => true,
            "restaurant_id" => 23,
            "description" => "Nachos, cipolla rosa, jalapeno, datterini, formaggio filante, guacamole e panna acida",
            "price" => 10,
        ],
        [
            "name" => "Pollo Botanero",
            "img" => "uploads/Piedra_del_Sol_Pollo_Botanero.jpg",
            "isVisible" => true,
            "restaurant_id" => 23,
            "description" => "Gustose cosce di pollo marinate e fritte",
            "price" => 10.5,
        ],
        [
            "name" => "Arranchera Nortena",
            "img" => "uploads/Piedra_del_Sol_arrachera.jpg",
            "isVisible" => true,
            "restaurant_id" => 23,
            "description" => "Taglio di carne tipico Messicano, alla griglia. Servito con crema di fagioli, guacamole e insalata",
            "price" => 25,
        ],
        [
            "name" => "Camaron Salteados",
            "img" => "uploads/Piedra_del_Sol_Camarones-Salteados.webp",
            "isVisible" => true,
            "restaurant_id" => 23,
            "description" => "Sfoglia di grano ripiena con mazzancolle saltate, panna acida, crautri, lime e guacamole",
            "price" => 10.5,
        ],
        [
            "name" => "Parillada",
            "img" => "uploads/Piedra_del_Sol_Parillada.jpeg",
            "isVisible" => true,
            "restaurant_id" => 23,
            "description" => "Gustoso mix di carne con Chorizo, Arrachera, Tapa de Asado",
            "price" => 60,
        ],
        // 24 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Nachos Chihuahua",
            "img" => "uploads/Chihuahua_Tacos_Nachos.png",
            "isVisible" => true,
            "restaurant_id" => 24,
            "description" => "Nachos, cipolla rosa, jalapeno, datterini, formaggio filante, guacamole e panna acida",
            "price" => 9,
        ],
        [
            "name" => "Buttido de Carnitas",
            "img" => "uploads/Chihuahua_Tacos_Carnitas-Burritos.jpg",
            "isVisible" => true,
            "restaurant_id" => 24,
            "description" => "Ripieno di gamberi, verdure, guacamole, chili, carne di pollo, di manzo e maiale",
            "price" => 8.5,
        ],
        [
            "name" => "Tacos Suadero",
            "img" => "uploads/Chihuahua_Tacos_SuaderoTacos.jpg",
            "isVisible" => true,
            "restaurant_id" => 24,
            "description" => "Gustoso taglio di manzo marinato",
            "price" => 13,
        ],
        [
            "name" => "Arranchera Nortena",
            "img" => "uploads/Chihuahua_Tacos_Arranchera_Nortena.jpg",
            "isVisible" => true,
            "restaurant_id" => 24,
            "description" => "Taglio di carne tipico Messicano, alla griglia. Servito con crema di fagioli, guacamole e insalata",
            "price" => 25,
        ],
        [
            "name" => "Camaron Salteados",
            "img" => "uploads/Chihuahua_Tacos_Camaron_Salteados.jpg",
            "isVisible" => true,
            "restaurant_id" => 24,
            "description" => "Sfoglia di grano ripiena con mazzancolle saltate, panna acida, crautri, lime e guacamole",
            "price" => 10.5,
        ],
        [
            "name" => "Choco Tacos",
            "img" => "uploads/Chihuahua_Tacos_Choco_Tacos.webp",
            "isVisible" => true,
            "restaurant_id" => 24,
            "description" => "Gustoso tacos con ripieno di cioccolato",
            "price" => 4,
        ],
        // MANUEL
        // 25 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Tentacolo",
            "restaurant_id" => 25,
            "img" => "uploads/Panino-con-polpo.jpg",
            "isVisible" => true,
            "description" => "polpo cotto al vapore e poi grigliato, cipolla di di tropea in agrodolce, capperi e olio extravergine d'oliva",
            "price" => 15.00,
        ],
        [
            "name" => "Baccalà",
            "restaurant_id" => 25,
            "img" => "uploads/panino-baccala-pastellato.jpg",
            "isVisible" => true,
            "description" => "filetto di merluzzo alla piastra con crema di olive nere e pomodori secchi",
            "price" => 14.00,
        ],
        [
            "name" => "Mazara",
            "restaurant_id" => 25,
            "img" => "uploads/panino-gamberi-uno.jpg",
            "isVisible" => true,
            "description" => "gamberi rossi di Mazara crudi, rucola, lime, sale, pepe e olio",
            "price" => 16.00,
        ],
        [
            "name" => "Senza via di scampo",
            "restaurant_id" => 25,
            "img" => "uploads/panino-scampi.jpg",
            "isVisible" => true,
            "description" => "scampi crudi, rucola, lime, sale, olio e pepe",
            "price" => 15.00,
        ],
        [
            "name" => "Squid",
            "restaurant_id" => 25,
            "img" => "uploads/panino-seppioline.jpg",
            "isVisible" => true,
            "description" => "seppioline grigliate, crema di carciofi, sale, olio, pepe",
            "price" => 13.00,
        ],
        [
            "name" => "Tonno",
            "restaurant_id" => 25,
            "img" => "uploads/panino-tonno.jpg",
            "isVisible" => true,
            "description" => "Filetto di tonno crudo, insalata, pomodorini, sale, pepe, olio",
            "price" => 14.00,
        ],
        // 26 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Borger Caramel",
            "restaurant_id" => 26,
            "img" => "uploads/Hamburger-con-bacon-1.jpg",
            "isVisible" => true,
            "description" => "Pan brioche artigianale, hamburger di bufalo, formaggio cheddar, bacon croccante, maionese gastronomica, cipolla caramellata, pesto artigianale al basilico e rucola",
            "price" => 11.00,
        ],
        [
            "name" => "Borger Cheese",
            "restaurant_id" => 26,
            "img" => "uploads/panino-con-tomino.jpg",
            "isVisible" => true,
            "description" => "Pan brioche artigianale, tomino piemontese filante, speck di Sauris, maionese gastronomica e noci tostate",
            "price" => 11.50,
        ],
        [
            "name" => "Truffle Borger",
            "restaurant_id" => 26,
            "img" => "uploads/hamburger-uovo.jpg",
            "isVisible" => true,
            "description" => "Pan brioche artigianale, hamburger di bufalo, uova strapazzate, crema al tartufo, maionese gastronomica",
            "price" => 12.00,
        ],
        [
            "name" => "Green Cheese Borger",
            "restaurant_id" => 26,
            "img" => "uploads/hamburger-vegan.webp",
            "isVisible" => true,
            "description" => "Pan brioche artigianale, hamburger vegetale fatto in casa (spinaci, patata e piselli), maionese gastronomica, nocciole tostate, formaggio filante, pomodoro, insalata, cipolla caramellata",
            "price" => 10.50,
        ],
        [
            "name" => "Chicken WoW Borger",
            "restaurant_id" => 26,
            "img" => "uploads/chicken-burger.jpg",
            "isVisible" => true,
            "description" => "Pan brioche artigianale, pollo impanato nel panko e fritto fatto in casa, maionese gastronomica, pomodori freschi, foglia di insalata romana",
            "price" => 11.50,
        ],
        [
            "name" => "Pulled Pork Borger",
            "restaurant_id" => 26,
            "img" => "uploads/pulled.jpeg",
            "isVisible" => true,
            "description" => "Pan brioche artigianale, pulled pork cotto a bassa temperatura, salsa bbq, cetrioli e cappuccio viola al gin mare",
            "price" => 12.00,
        ],
        // 27 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Trapizzino Pollo Cacciatora",
            "restaurant_id" => 27,
            "img" => "uploads/trapizzino-pollo-cacciatora-1.jpg",
            "isVisible" => true,
            "description" => "IL PRIMO NATO! - Ingredienti:Pollo, Olio evo, Sale, Pepe, Rosmarino, Aglio,  Aceto, Vino bianco.",
            "price" => 5.0,
        ],
        [
            "name" => "Trapizzino Polpette Sugo",
            "restaurant_id" => 27,
            "img" => "uploads/trapizzino-polpetta-sugo.jpg",
            "isVisible" => true,
            "description" => "COME LA FACEVA NONNA - Ingredienti:Pomodori Pelati, Carne di manzo, Pane, Olio evo, Grana Padano, Prezzemolo, Sale, Cipolla, Sedano, Carota, Uovo, Basilico, Aglio, Pepe, Noce moscata.",
            "price" => 5.00,
        ],
        [
            "name" => "Trapizzino Parmigiana Melanzane",
            "restaurant_id" => 27,
            "img" => "uploads/trapizzino-parmigiana-melanzane.jpg",
            "isVisible" => true,
            "description" => "CON MELANZANE COTTE AL FORNO -Ingredienti:Melanzane, Olio evo, Cipolla, Basilico, Sale, Pomodoro, Parmigiano, Mozzarella.",
            "price" => 5.00,
        ],
        [
            "name" => "Trapizzino Lingua Salsa Verde",
            "restaurant_id" => 27,
            "img" => "uploads/trapizzino-lingua-salsa-verde.jpg",
            "isVisible" => true,
            "description" => "A TEMPERATURA AMBIENTE - Ingredienti: Lingua bollita; Salsa verde: Prezzemolo, Alici,  Aglio, Capperi, Olive, Olio  evo, Aceto, Pane Sale e Pepe.",
            "price" => 5.00,
        ],
        [
            "name" => "Trapizzino Doppia Panna Alici",
            "restaurant_id" => 27,
            "img" => "uploads/trapizzino-doppia-panna-alici.jpg",
            "isVisible" => true,
            "description" => "PANNA SOTTO-SOPRA COME IL GELATO A ROMA - Stracciatella di burrata con Alici",
            "price" => 5.00,
        ],
        [
            "name" => "Trapizzino Zighini",
            "restaurant_id" => 27,
            "img" => "uploads/trapizzino-zighini.jpg",
            "isVisible" => true,
            "description" => "Carne di manzo, Berbere, Pomodoro, Olio evo, Sale, Cipolla.",
            "price" => 5.00,
        ],
        // 28 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Involtini Primavera",
            "restaurant_id" => 28,
            "img" => "uploads/Involtini-primavera-vegetariani.jpg",
            "isVisible" => true,
            "description" => "Gli Involtini primavera sono un antipasto delizioso tipico della cucina cinese, amatissimo in tutto il mondo!",
            "price" => 7.00,
        ],
        [
            "name" => "Spaghetti di Soia",
            "restaurant_id" => 28,
            "img" => "uploads/spaghetti-di-soia.jpg",
            "isVisible" => true,
            "description" => "Un piatto di noodles dal vero sapore orientale, arricchito con carote, zucchine, peperoni e cipolle, oltre all'immancabile salsa di soia e al tocco speciale dell'olio di sesamo",
            "price" => 7.00,
        ],
        [
            "name" => "Spaghetti di riso con carne e verdure",
            "restaurant_id" => 28,
            "img" => "uploads/Spaghetti-di-riso-con-carne-e-verdure-min.jpg",
            "isVisible" => true,
            "description" => "La ricetta cinese degli spaghetti di riso con carne e verdure è tipica di molte regioni, in ognuna delle quali viene preparata con tempi, modalità e ingredienti diversi.",
            "price" => 8.0,
        ],
        [
            "name" => "Ravioli Cinesi al Vapore",
            "restaurant_id" => 28,
            "img" => "uploads/Ravioli-al-vapore-cinesi.jpg",
            "isVisible" => true,
            "description" => "Sono tipici del Capodanno cinese, come gli involtini primavera, ma vengono consumati durante tutte le festività perché la loro forma, che ricorda quella di un'antica moneta, è considerata un simbolo di buona fortuna.",
            "price" => 8.00,
        ],
        [
            "name" => "Wonton Fritti",
            "restaurant_id" => 28,
            "img" => "uploads/wonton-fritti.jpg",
            "isVisible" => true,
            "description" => "Solitamente vengono serviti come antipasto caldo insieme a involtini primavera e toast di gamberi e rappresentano un grande classico della cucina cinese.",
            "price" => 7.00,
        ],
        [
            "name" => "Wonton Soup",
            "restaurant_id" => 28,
            "img" => "uploads/pork-wonton-in-chicken-broth-scaled.jpg",
            "isVisible" => true,
            "description" => "I wonton sono dei ravioli a base di farina e acqua che possono essere fritti oppure lessati e serviti in brodo.",
            "price" => 14.00,
        ],
        // 29 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Pollo alle Mandorle",
            "restaurant_id" => 29,
            "img" => "uploads/pollo-alle-mandorle.jpg",
            "isVisible" => true,
            "description" => "Tipico della cucina casalinga del Guangdong, il pollo alle mandorle è una ricetta molto apprezzata in tutto il mondo che non manca mai nel menù dei ristoranti cinesi.",
            "price" => "11.00",
        ],
        [
            "name" => "Maiale in Agrodolce",
            "restaurant_id" => 29,
            "img" => "uploads/maiale-agrodolce.webp",
            "isVisible" => true,
            "description" => "Il maiale in agrodolce è una ricetta della tradizione che rappresenta perfettamente questa caratteristica, a partire dalla scelta degli ingredienti: il verde dei peperoni, il rosso del pomodoro e il giallo dell’ananas, un mix dalle tinte vivaci che, insieme alla salsa agrodolce, conferisce al piatto il suo gusto inconfondibile.",
            "price" => 11.50,
        ],
        [
            "name" => "Riso alla Cantonese",
            "restaurant_id" => 29,
            "img" => "uploads/Riso-alla-cantonese-Ricetta-Riso-cantonese-.webp",
            "isVisible" => true,
            "description" => "Il riso alla cantonese è una delle pietanze che ordiniamo più spesso al ristorante cinese, ma spesso non viene considerato un vero piatto della tradizione. In realtà in Cina è molto diffuso e viene servito come accompagnamento alle portate principali, al pari del pane in Occidente.",
            "price" => 12.00,
        ],
        [
            "name" => "Pollo al Limone",
            "restaurant_id" => 29,
            "img" => "uploads/pollo-al-limone4-min.webp",
            "isVisible" => true,
            "description" => " In questa ricetta ci rivolgiamo a chi adora il gusto agrumato: pollo al limone. Tenere striscioline di petto di pollo tuffate in una cremina densa e avvolgente che renderà questo secondo piatto davvero irresistibile e profumato.",
            "price" => 10.50,
        ],
        [
            "name" => "Gnocchi di Riso con Verdure",
            "restaurant_id" => 29,
            "img" => "uploads/gnocchi-riso-verdure.jpg",
            "isVisible" => true,
            "description" => " Gli gnocchi di riso hanno una consistenza più gommosa rispetto ai nostri tradizionali gnocchi di patate, che si sposa perfettamente con la croccantezza delle verdure saltate nel wok.",
            "price" => 11.50,
        ],
        [
            "name" => "Gelato Fritto",
            "restaurant_id" => 29,
            "img" => "uploads/gelato-fritto-cinese-9566-621x932.jpg",
            "isVisible" => true,
            "description" => "Come sempre, nella cucina cinese le consistenze svolgono un ruolo fondamentale: sotto all'involucro caldo e croccante si nasconde un cuore freddo e cremoso di gelato alla crema ricoperto da uno strato di soffice pan di spagna.",
            "price" => 12.00,
        ],
        // 30 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Gamberi in Salsa Piccante",
            "restaurant_id" => 30,
            "img" => "uploads/gamberi-piccante.jpg",
            "isVisible" => true,
            "description" => "I gamberi in salsa piccante sono un piatto tipico della tradizione cinese, diffuso soprattutto nella provincia di Sichuan.",
            "price" => 5.00,
        ],
        [
            "name" => "Pak choi in wok",
            "restaurant_id" => 30,
            "img" => "uploads/Pak-choi.jpg",
            "isVisible" => true,
            "description" => "Il pak choi (o bok choi) è una varietà di cavolo cinese che si può cucinare in vari modi: al vapore, al forno o saltato in padella, anzi nel wok!",
            "price" => 5.00,
        ],
        [
            "name" => "Zongzi",
            "restaurant_id" => 30,
            "img" => "uploads/Zongzi-two-ways-portrait4.jpg",
            "isVisible" => true,
            "description" => "Fra i piatti tipici della cucina cinese ce ne sono alcuni particolarmente legati alla tradizione, come per esempio i zongzi, una sorta di involtini di riso glutinoso avvolti da foglie di bambù.",
            "price" => 5.00,
        ],
        [
            "name" => "Ravioli Shao Mai",
            "restaurant_id" => 30,
            "img" => "uploads/shao-mai.jpg",
            "isVisible" => true,
            "description" => "I ravioli Shao Mai sono uno dei piatti più popolari e iconici della cucina cinese: si tratta di un particolare tipo di raviolo al vapore dalla forma speciale che ricorda un fiore, dal gusto inconfondibile.",
            "price" => 5.00,
        ],
        [
            "name" => "Noodles fritti alle verdure",
            "restaurant_id" => 30,
            "img" => "uploads/noodles-fritti.webp",
            "isVisible" => true,
            "description" => "I noodles fritti alle verdure sono un primo piatto della cucina asiatica. Nella ricetta che vi proponiamo i noodles vengono fritti, ma questo tipo di pasta si presta anche ad essere lessata e poi saltata in padella con il sugo per essere insaporita.",
            "price" => 5.00,
        ],
        [
            "name" => "Fragole Caramellate",
            "restaurant_id" => 30,
            "img" => "uploads/fragole-caramellate.jpg",
            "isVisible" => true,
            "description" => "Conosciuta come tanghulu, la frutta caramellata è una ricetta espressa che si realizza con spiedini di bambù in cui si infilzano bocconcini di frutta da ricoprire con un sottile caramello.",
            "price" => 5.00,
        ],
        // MATTIA
        // 31 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Sashimi di salmone",
            "img" => "uploads/sashimi-salmone.jpg",
            "isVisible" => true,
            "description" => "4 pezzi",
            "price" => 11.00,
            "restaurant_id" => 31
        ],
        [
            "name" => "Nigiri sake",
            "img" => "uploads/nigiri-sake.jpg",
            "isVisible" => true,
            "description" => "2 pezzi",
            "price" => 5.00,
            "restaurant_id" => 31
        ],
        [
            "name" => "Maki rolls philadelphia",
            "img" => "uploads/maki-rolls-philadelphia.jpg",
            "isVisible" => true,
            "description" => "8 pezzi. Alghe, riso, salmone, philadelphia",
            "price" => 8.00,
            "restaurant_id" => 31
        ],
        // 32 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "YASAI TEMAKI",
            "img" => "uploads/yasai-temaki.jpg",
            "isVisible" => true,
            "description" => "Cono di alga con riso e misto vegetariano",
            "price" => 4.50,
            "restaurant_id" => 32
        ],
        [
            "name" => "MIX MAKI",
            "img" => "uploads/mix-maki.jpg",
            "isVisible" => true,
            "description" => "Riso, tonno, salmone e cetriolo",
            "price" => 5.00,
            "restaurant_id" => 32
        ],
        [
            "name" => "URA YASAI",
            "img" => "uploads/ura-yasai.jpg",
            "isVisible" => true,
            "description" => "Rotolini di riso esterno e con verdure e filetti di pesce crudo o tempura all’interno. Riso e misto vegetariano",
            "price" => 8.00,
            "restaurant_id" => 32
        ],
        // 33 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "EBI TEMPURA",
            "img" => "uploads/ebi-tempura.jpg",
            "isVisible" => true,
            "description" => "Gamberoni fritti con pastella leggera (Pezzi 5)",
            "price" => 12.00,
            "restaurant_id" => 33
        ],
        [
            "name" => "Nigiri EBI",
            "img" => "uploads/sushi-ebi.jpg",
            "isVisible" => true,
            "description" => "Nigiri di gambero cotto",
            "price" => 2.00,
            "restaurant_id" => 33
        ],
        [
            "name" => "Riso bianco e sesamo",
            "img" => "uploads/riso-bianco-e-sesamo.jpg",
            "isVisible" => true,
            "description" => "Ciotola di riso bianco e sesamo",
            "price" => 2.50,
            "restaurant_id" => 33
        ],
        // 34 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Torta della nonna",
            "img" => "uploads/torta-della-nonna.jpg",
            "isVisible" => true,
            "description" => "La torta della nonna è un dolce che, nel corso degli anni, è diventato parte integrante della cucina tipica toscana. La torta ha avuto, probabilmente per la sua complessità, un successo tale da diventare un classico, proposto nella grande maggioranza dei locali di ristorazione, soprattutto negli anni 80 e 90 del XX secolo.",
            "price" => 6.00,
            "restaurant_id" => 34
        ],
        [
            "name" => "Waffle",
            "img" => "uploads/waffle.jpg",
            "isVisible" => true,
            "description" => "Il Waffle, altrimenti noto come wafel, waffel o ancora gaufre, è un dolce a cialda (che ne è la traduzione esatta), croccante fuori e morbido dentro, cotto su doppie piastre roventi che gli conferiscono il caratteristico aspetto a grata.",
            "price" => 5.00,
            "restaurant_id" => 34
        ],
        [
            "name" => "Cornetto semplice",
            "img" => "uploads/cornetto.jpg",
            "isVisible" => true,
            "description" => "Si tratta di una specialità alimentare dolce o salata a forma di mezzaluna; la sua composizione è a base di: farina, burro, uova, acqua e zucchero, con l'aggiunta di tuorlo d'uovo spalmato sulla superficie per ottenere una colorazione più dorata.",
            "price" => 1.00,
            "restaurant_id" => 34
        ],
        [
            "name" => "Sacher",
            "img" => "uploads/sacher.jpg",
            "isVisible" => true,
            "description" => "La torta Sacher è una torta al cioccolato inventata dal pasticciere, allora sedicenne, Franz Sacher per il principe Klemens von Metternich il 9 luglio 1832 a Vienna, in Austria.",
            "price" => 6.50,
            "restaurant_id" => 34
        ],
        [
            "name" => "Brownie",
            "img" => "uploads/brownie.jpg",
            "isVisible" => true,
            "description" => "Il brownie, noto anche come chocolate brownie o Manchester brownie, è un biscotto al cioccolato, tipico dessert della cucina statunitense, chiamato così per via del suo colore scuro. È un biscotto tagliato a piccoli quadrettini.",
            "price" => 4.00,
            "restaurant_id" => 34
        ],
        [
            "name" => "Frappé",
            "img" => "uploads/frappe.jpg",
            "isVisible" => true,
            "description" => "Tradotto dall'inglese-Un milkshake è una bevanda dolce ottenuta mescolando latte, gelato e aromi o dolcificanti come caramello, salsa al caramello, sciroppo di cioccolato, sciroppo di frutta o frutta intera in una miscela densa, dolce e fredda.",
            "price" => 4.50,
            "restaurant_id" => 34
        ],
        // 35 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Tiramisù",
            "img" => "uploads/tiramisu.jpg",
            "isVisible" => true,
            "description" => "Il tiramisù è un dolce e prodotto agroalimentare tradizionale diffuso in tutto il territorio italiano, le cui origini sono dibattute e attribuite soprattutto al Veneto e al Friuli-Venezia Giulia.",
            "price" => 5.00,
            "restaurant_id" => 35
        ],
        [
            "name" => "New York Cheesecake",
            "img" => "uploads/ny-cheesecake.jpg",
            "isVisible" => true,
            "description" => "La New York cheesecake è una cheesecake con base biscotti e farcitura alta, ma cotta a lungo in forno.",
            "price" => 4.50,
            "restaurant_id" => 35
        ],
        [
            "name" => "Tortino di cioccolato con cuore fondente",
            "img" => "uploads/tortino-fondente.jpg",
            "isVisible" => true,
            "description" => "I tortini di cioccolato con cuore fondente sono un dessert dalla dolce sorpresa: il cuore di cioccolato fuso è una tentazione per tutti, e voi sarete osannati come grandi chef!",
            "price" => 3.50,
            "restaurant_id" => 35
        ],
        // 36 --------------------------------------------------------------------------------------------------------------
        [
            "name" => "Torta di mele",
            "img" => "uploads/torta-di-mele.jpg",
            "isVisible" => true,
            "description" => "Le mele da sempre sono protagoniste indiscusse dei dolci casalinghi, come la nostra torta di mele, golosa, soffice e aromatica, è il miglior comfort food che si possa desiderare!",
            "price" => 4.00,
            "restaurant_id" => 36
        ],
        [
            "name" => "Muffin con gocce di cioccolato",
            "img" => "uploads/muffin-con-gocce-di-cioccolato.jpg",
            "isVisible" => true,
            "description" => "Questi muffin senza burro sono perfetti gustosi ma non pesanti, ottimi accompagnati da un buon cappuccino o caffè.",
            "price" => 2.00,
            "restaurant_id" => 36
        ],
        [
            "name" => "Banana bread",
            "img" => "uploads/banana-bread.jpg",
            "isVisible" => true,
            "description" => "Il Banana bread è uno dei dolci americani che ha conosciuto maggiore fama all’estero. Merito di una ricetta facilissima da fare e anche molto furba, perché ti permette di riciclare facilmente delle banane troppo mature per essere consumate al naturale. ",
            "price" => 4.00,
            "restaurant_id" => 36
        ],
    ]
];
