<?php
return [
    "restaurants" => [
        // STEFANIA
        [ // 1
            "name" => "Ristorante Metropolitan",
            "email" => "ristorante-metropolitan@metropolitan.it",
            "password" => "12345678",
            "telephone" => "02 66717715",
            "iva" => "33115566991",
            "address" => "via Melchiorre Gioia, 73, 20124 Milano",
            "img" => "uploads/metropolitan.jpg",
            "categories" => [1],
        ],
        [ // 2
            "name" => "Ristorante pizzeria La Bambarra",
            "email" => "pizzeriabambarrabologna@libero.it",
            "password" => "123123123123",
            "telephone" => "051 5870544",
            "iva" => "99663344881",
            "address" => "via Cleto Tomba, 14A, 40127 Bologna",
            "img" => "uploads/bambarra.jpg",
            "categories" => [1, 2],
        ],
        [ // 3
            "name" => "Antica Pizzeria Regina Margherita",
            "email" => "antica-reginamargherita@gmail.com",
            "password" => "123123123123",
            "telephone" => "081 764 4629",
            "iva" => "21602207388",
            "address" => " Via Partenope, 19, 80122 Napoli NA",
            "img" => "uploads/reginamargherita.jpg",
            "categories" => [2],
        ],
        [ // 4
            "name" => "Pizzeria Fra Diavolo",
            "email" => "info@pizzeriafradiavolo.it",
            "password" => "123123123123",
            "telephone" => "011 819 2602",
            "iva" => "77663344668",
            "address" => " Piazza Gran Madre di Dio, 4A, 10131 Torino TO",
            "img" => "uploads/fradiavolo.jpg",
            "categories" => [2],
        ],
        [ // 5
            "name" => "Trattoria San Biagio",
            "email" => "trattoriasanbiagiomodena@alice.it",
            "password" => "12345678",
            "telephone" => "059 236106",
            "iva" => "55773311005",
            "address" => "via Masini, 45, 20124 Modena",
            "img" => "uploads/sanbiagio.jpg",
            "categories" => [1]
        ],
        [ // 6
            "name" => "Ristorante Pizzeria Malerba",
            "email" => "malerbaveganristorante@malerba.it",
            "password" => "12345678",
            "telephone" => "04 98205111",
            "iva" => "99551133884",
            "address" => "via Giuseppe Massasenti, 26C, 20124 Padova",
            "img" => "uploads/malerba.jpg",
            "categories" => [1, 13, 2]
        ],
        [ // 7
            "name" => "Bar Bistrot Soul Green",
            "email" => "vegan@soulgreenbistrot.it",
            "password" => "12345678",
            "telephone" => "02 62695162",
            "iva" => "77889933221",
            "address" => "Piazzale Principessa Clotilde, 2, 20124 Milano",
            "img" => "uploads/soulgreen.jpg",
            "categories" => [13]
        ],
        [ // 8
            "name" => "Hostaria Grappolo D'Oro",
            "email" => "hostariagrappolodororoma@tiscali.it",
            "password" => "12345678",
            "telephone" => "06 689 7080",
            "iva" => "00005566881",
            "address" => "Piazza della Cancelleria 80, 00100, Roma",
            "img" => "uploads/grappolo.jpg",
            "categories" => [1]
        ],
        [ // 9
            "name" => "Flower Burger",
            "email" => "smile@flowerburger.it",
            "password" => "12345678",
            "telephone" => "051 232041",
            "iva" => "99999988445",
            "address" => "Via Riva di Reno, 118p, 40121 Livorno",
            "img" => "uploads/flower.jpg",
            "categories" => [13]
        ],
        // CRISTIAN
        [ // 10
            "name" => "Poke House",
            "email" => "gambero@pokehouse.it",
            "password" => "12345678",
            "telephone" => "0697993054",
            "iva" => "10300540969",
            "address" => "Via del Gambero, 36",
            "img" => "uploads/store_poke_1.jpg",
            "categories" => [4],
        ],
        [ // 11
            "name" => "Pokèria by NIMA",
            "email" => "info@pokeria.com",
            "password" => "12345678",
            "telephone" => "0298670010",
            "iva" => "03760030134",
            "address" => "Via Flaminia, 488",
            "img" => "uploads/pokeria-by-nima.jpg",
            "categories" => [4],
        ],
        [ // 12
            "name" => "Kebhouze",
            "email" => "work@kebhouze.com",
            "password" => "12345678",
            "telephone" => "0644232764",
            "iva" => "16271141000",
            "address" => "Via Alberto Lionello, 201",
            "img" => "uploads/kebhouze.jpeg",
            "categories" => [11],
        ],
        [ // 13
            "name" => "Mr Kebab Turco",
            "email" => "info@mrkebab.com",
            "password" => "12345678",
            "telephone" => "0633252764",
            "iva" => "17271141010",
            "address" => "Via Cassia, 101",
            "img" => "uploads/turco.png",
            "categories" => [11],
        ],
        [ // 14
            "name" => "Kebab Siria",
            "email" => "info@kebabsiria.com",
            "password" => "12345678",
            "telephone" => "0633255564",
            "iva" => "17271561010",
            "address" => "Via Stimigliano 1",
            "img" => "uploads/siria.jpeg",
            "categories" => [11],
        ],
        [ // 15
            "name" => "Ali Babà Kebab",
            "email" => "info@kalibabakebab.com",
            "password" => "52345578",
            "telephone" => "0633255565",
            "iva" => "17271561011",
            "address" => "Via Carroceto 96",
            "img" => "uploads/ali-baba.jpg",
            "categories" => [11],
        ],
        [ // 16
            "name" => "CurryMania!",
            "email" => "info@currymania.com",
            "password" => "12345678",
            "telephone" => "0645262764",
            "iva" => "16291041000",
            "address" => "Via Salaria, 123",
            "img" => "uploads/indian.jpeg",
            "categories" => [5],
        ],
        [ // 17
            "name" => "Jaipur",
            "email" => "info@cjaipur.com",
            "password" => "12345678",
            "telephone" => "0645299764",
            "iva" => "16291041990",
            "address" => "Via San Francesco a Ripa 56",
            "img" => "uploads/jaipur.jpeg",
            "categories" => [5],
        ],
        [ // 18
            "name" => "Himalaya's Kashmir",
            "email" => "info@Kashmir.com",
            "password" => "12345678",
            "telephone" => "0666262764",
            "iva" => "16291041899",
            "address" => "Via Principe Amedeo 325",
            "img" => "uploads/kashmir.jpeg",
            "categories" => [5],
        ],
        // FEDERICO
        [ // 19
            "name" => "Vasiliki Kouzina",
            "email" => "VasilikiKouzina@gmail.com",
            "password" => "12345678",
            "telephone" => "39 02 9438 1405",
            "iva" => "12345678901",
            "address" => "Via Clusone, 6 20135, Milano",
            "img" => "uploads/Vasiliki_kouzina_milano.jpg",
            "categories" => [9],
        ],
        [ // 20
            "name" => "Ristorante Greco Dioniso",
            "email" => "GrecoDioniso@gmail.com",
            "password" => "12345678",
            "telephone" => "+39 055 217882",
            "iva" => "12345678902",
            "address" => "Via Mino da Fiesole, 15, Firenze",
            "img" => "uploads/Ristorante_Greco_Dioniso.jpg",
            "categories" => [9],
        ],
        [ // 21
            "name" => "Taverna Ouzeri Mykonos",
            "email" => "OuzeriMykonos@gmail.com",
            "password" => "12345678",
            "telephone" => "+39 393 33 66 886",
            "iva" => "12345678903",
            "address" => "Via Fratelli Bandiera, 1, 42124 Reggio Emilia",
            "img" => "uploads/Taverna_Ouzeri_Mykonos.webp",
            "categories" => [9],
        ],
        [ // 22
            "name" => "El Takomaki",
            "email" => "Takomaki@gmail.com",
            "password" => "12345678",
            "telephone" => "+39 393 33 66 887",
            "iva" => "12345678904",
            "address" => "El Tacomaki, Via Giovanni Battista Fauchè, 11 20154 Milano",
            "img" => "uploads/El_Takomaki.jpg",
            "categories" => [10],
        ],
        [ // 23
            "name" => "Piedra del Sol",
            "email" => "DelSol@gmail.com",
            "password" => "12345678",
            "telephone" => "+39 393 33 66 885",
            "iva" => "12345678905",
            "address" => "Piedra del Sol Via Emilio Cornalia, 2 20124 Milano",
            "img" => "uploads/Piedra_del_Sol.jpg",
            "categories" => [10],
        ],
        [ // 24
            "name" => "Chihuahua Tacos",
            "email" => "Chihuahua@gmail.com",
            "password" => "12345678",
            "telephone" => "+39 393 33 66 883",
            "iva" => "12345678906",
            "address" => "Chihuahua Tacos - Sarpi Via Paolo Sarpi, 60 20154 Milano",
            "img" => "uploads/Chihuahua_Tacos.webp",
            "categories" => [10],
        ],
        // MANUEL
        [ // 25
            "name" => "Panini di Mare",
            "email" => "paninidimare1@gmail.com",
            "password" => "12345678",
            "telephone" => "0123456789",
            "iva" => "11111111112",
            "address" => "via dei ristoranti, 20, Roma",
            "img" => "uploads/panini-di-mare.jpg",
            "categories" => [6, 1],
        ],
        [ // 26
            "name" => "Borger",
            "email" => "paninidimare2@gmail.com",
            "password" => "12345678",
            "telephone" => "0123456789",
            "iva" => "11111111113",
            "address" => "via dei ristoranti, 21, Roma",
            "img" => "uploads/borger.jpg",
            "categories" => [6],
        ],
        [ // 27
            "name" => "Trapizzino",
            "email" => "paninidimare3@gmail.com",
            "password" => "12345678",
            "telephone" => "0123456789",
            "iva" => "11111111114",
            "address" => "via dei ristoranti, 22, Roma",
            "img" => "uploads/trapizzino.webp",
            "categories" => [6],
        ],
        [ // 28
            "name" => "La Grande Muraglia",
            "email" => "paninidimare4@gmail.com",
            "password" => "12345678",
            "telephone" => "0123456789",
            "iva" => "11111111115",
            "address" => "via dei ristoranti, 23, Roma",
            "img" => "uploads/la-grande-muraglia.jpg",
            "categories" => [8, 3],
        ],
        [ // 29
            "name" => "Little Beijing",
            "email" => "paninidimare5@gmail.com",
            "password" => "12345678",
            "telephone" => "0123456789",
            "iva" => "11111111116",
            "address" => "via dei ristoranti, 24, Roma",
            "img" => "uploads/ris-b.jpg",
            "categories" => [8, 3],
        ],
        [ // 30
            "name" => "Mora Cinese",
            "email" => "paninidimare6@gmail.com",
            "password" => "12345678",
            "telephone" => "0123456789",
            "iva" => "11111111117",
            "address" => "via dei ristoranti, 25, Roma",
            "img" => "uploads/mora-cinese.webp",
            "categories" => [8, 3],
        ],
        // MATTIA
        [ // 31
            "name" => "Boa Sorte",
            "email" => "boa@gmail.com",
            "password" => "12345678",
            "telephone" => "0687888921",
            "iva" => "11111111118",
            "address" => "Via della Colonna Antonina, 48/49, Roma, 00186",
            "img" => "uploads/boa-sorte.jpg",
            "categories" => [7, 3],
        ],
        [ // 32
            "name" => "Gado Sensei",
            "email" => "gado@gmail.com",
            "password" => "12345678",
            "telephone" => "0698188299",
            "iva" => "11111111119",
            "address" => "Via delle Sette Chiese 50, Roma, 00145",
            "img" => "uploads/gado-sensei.jpg",
            "categories" => [7, 3],
        ],
        [ // 33
            "name" => "Kisaki Ramen & Sushi",
            "email" => "kisaki@gmail.com",
            "password" => "12345678",
            "telephone" => "066785838",
            "iva" => "11111111123",
            "address" => "Piazza Capranica 75, Roma, 00186",
            "img" => "uploads/kisaki.jpg",
            "categories" => [7, 3],
        ],
        [ // 34
            "name" => "Bakery House",
            "email" => "bakery@gmail.com",
            "password" => "12345678",
            "telephone" => "0692110842",
            "iva" => "11111111124",
            "address" => "Viale America 89, Roma, 00144",
            "img" => "uploads/bakery.jpg",
            "categories" => [12],
        ],
        [ // 35
            "name" => "Maat",
            "email" => "maat@gmail.com",
            "password" => "12345678",
            "telephone" => "0671583467",
            "iva" => "11111111136",
            "address" => "Via Sestio Calvino 20, Roma, 00174",
            "img" => "uploads/maat.jpg",
            "categories" => [12],
        ],
        [ // 36
            "name" => "Gelateria Torcè",
            "email" => "torce@gmail.com",
            "password" => "12345678",
            "telephone" => "0697882939",
            "iva" => "11111111190",
            "address" => "Viale dell'Aeronautica, 105, 00144 Roma RM",
            "img" => "uploads/torce.jpg",
            "categories" => [12],
        ],
    ]
];
